/*
 Distinct powers
Problem 29 
Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:

2 2=4, 2 3=8, 2 4=16, 2 5=32
3 2=9, 3 3=27, 3 4=81, 3 5=243
4 2=16, 4 3=64, 4 4=256, 4 5=1024
5 2=25, 5 3=125, 5 4=625, 5 5=3125

If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

*/

#import <stdio.h>

int factors[10000000];
int n_sum = 0;
int n_factors[10000];
int n_numbers = 0;

void factorization(int a, int b, int *arr, int *n)
{
    int m = 0;
    
    for (int i = 2; i < 100; i++)
    {
        if (a % i == 0)
        {
            for (int j = 0; j < b; j++)
            {
                arr[m] = i;
                m++;
            }
            a/= i;
            i--;
        }
        
        if (a == 0)
            break;
    }
    *n = m;
}

int is_equal(int *arr_1, int *arr_2, int n)
{
    for (int i = 0; i <= n; i++)
    {
        if (arr_1[i] != arr_2[i])
            return 0;
    }
    return 1;
}

void insert(int a, int b)
{
    int ins = 1;
    
    int n = 0;
    int c_factors[10000];
    
    factorization(a, b, c_factors, &n);
    
    int c_index = 0;
    
    for (int i = 0; i < n_numbers; i++)
    {
        if (n_factors[i] == n)
        {
            for (int j = 0; j <= n; j++)
            {
                if (j == n)
                {
                    ins = 0;
                    break;
                }
                
                if (factors[j+c_index] != c_factors[j])
                {
                    break;
                }
            }
        }
        
        c_index += n_factors[i];
        
        if (!ins)
        {
            break;
        }
    }
    
    if (ins)
    {
        for (int i = 0; i < n; i++)
        {
            factors[i+n_sum] = c_factors[i];
        }
        n_sum += n;
        
        n_factors[n_numbers] = n;
        n_numbers++;
    }
}

int main()
{
    for (int a = 2; a < 101; a++)
    {
        for (int b = 2; b < 101; b++)
        {
            insert(a, b);
        }
    }
    
    printf("The number of different terms is %d\n", n_numbers);
}
