/*
 Triangular, pentagonal, and hexagonal
Problem 45 
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	  1, 3, 6, 10, 15, ...
Pentagonal	   Pn=n(3n−1)/2	 1, 5, 12, 22, 35, ...
Hexagonal	    Hn=n(2n−1)	   1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
*/

#include <stdio.h>

int is_pentagonal(long long x)
{
    static long long last_index = 0;
    
    long long last = last_index*(3*last_index-1)/2;
    
    while (last < x)
    {
        last_index++;
        last = last_index*(3*last_index-1)/2;
    }
    
    if (last == x)
    {
        return 1;
    }
    else
    {
        return 0;
    }
}

int is_hexagonal(long long x)
{
    static long long last_index = 0;
    
    long long last = last_index*(2*last_index-1);
    
    while (last < x)
    {
        last_index++;
        last = last_index*(2*last_index-1);
    }
    
    if (last == x)
    {
        return 1;
    }
    else
    {
        return 0;
    }
}

int main()
{
    long long result;
    long long n;
    for (n = 286;;n++)
    {
        long long c = n*(n+1)/2;
        
        //printf("triangle number: %lld\n", c);
        
        if (is_pentagonal(c))
        {
            if (is_hexagonal(c))
            {
                printf("the next triangle number that is also an pentagonal and hexagonal is %lld\n", c);
                result = c;
                break;
            }
        }
    }
    
    //printf("the next triangle number that is also an pentagonal and hexagonal is %d\n", result);
}
