/*
 Project Euler
 
 Problem 12
 
 Highly divisible triangular number
 
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/

#include <stdio.h>
/*
int primes[1000];

void compute_first_primes()
{
    int p = 2;
    primes[0] = 2;
    
    for (int i = 1; i < 1000; i++)
    {
        int found = 0;
        while (found == 0)
        {
            p++;
            for (int j = 0; j <= i; j++)
            {
                if (j == i)
                {
                    found = 1;
                    break;
                }
                
                if (p % primes[j] == 0)
                    break;
            }
            
            if (found)
            {
                primes[i] = p;
                break;
            }
        }
    }
}

*/

int number_of_factors(int x)
{
    /*
    naive solution
    int res = 0;
    
    for (int d = 1; d <= x; d++)
    {
        if (x % d == 0)
        {
            res++;
        }
    }
    
    return res;
    */
    
    
    //without precomputaion of primes
    int divisors[1000];
    divisors[0] = 1;
    
    int n_d = 1;
    
    for (int d = 2; x >= d;)
    {
        int i = 0;
        
        while (x % d == 0)
        {
            int temp = n_d;
            for (; i < temp; i++)
            {
                if (n_d == 500)
                    return 500;
                
                divisors[n_d] = divisors[i] * d;
                n_d++;
            }
            
            
            x /= d;
        }
        d++;
    }
    
    return n_d;
    
    /*
    //with precomputed primes
    int n_devisors = 1;
    
    for (int i = 0; x > 1; i++)
    {
        int n = n_devisors;
        
        while (x % primes[i] == 0)
        {
            n_devisors += n;
            x /= primes[i];
        }
    }
    
    return n_devisors;
    */
}

int main()
{
    int tri = 0;
    
    //compute_first_primes();
    
    
    for (int i = 1;;i++)
    {
        tri += i;
        
        if (number_of_factors(tri) >= 500)
            break;
    }
    
    printf("The first triangle number with over 500 divisors is %d\n", tri);
    
    printf("28 has %d factors \n", number_of_factors(28));
}
